spring.application.name=authsystem
spring.datasource.url=jdbc:postgresql://localhost:5432/auth
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379

# bpfm atwx dwir xrti : app password for mail
# Mail configuration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= enter your email address
spring.mail.password=mail app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
